ALTER TABLE "nodes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "nodes" FORCE ROW LEVEL SECURITY;

ALTER TABLE "node_positions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "node_positions" FORCE ROW LEVEL SECURITY;

ALTER TABLE "inputs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "inputs" FORCE ROW LEVEL SECURITY;

ALTER TABLE "outputs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "outputs" FORCE ROW LEVEL SECURITY;

ALTER TABLE "connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "connections" FORCE ROW LEVEL SECURITY;