ALTER TABLE "public"."nodes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."nodes" FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."node_positions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."node_positions" FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."inputs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."inputs" FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."outputs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."outputs" FORCE ROW LEVEL SECURITY;

ALTER TABLE "public"."connections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."connections" FORCE ROW LEVEL SECURITY;